# Database
db.url=jdbc:mysql://localhost:3306/codeforces_analyzer?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.username=root
db.password=Duc2006@
db.pool.size=10

# Google Gemini API
gemini.api.key=AIzaSyC6ux84Ymfi0KifMXc8313oHeKQmlT70to
gemini.model=models/gemini-flash-latest
gemini.max.tokens=2048

# Codeforces credentials
cf.login.email=bkdn25.Kira
cf.login.password=khanhdeptrai04062006

# Selenium Edge
edge.driver.path=C:/Users/admin/Downloads/edgedriver_win64/msedgedriver.exe
edge.headless=false

# Crawl schedule (Quartz cron)
crawl.cron=0 0 2 * * ?
crawl.max.submissions=5
crawl.delay.min.ms=500
crawl.delay.max.ms=1500